### ISSUE TITLE
IMAGE STUCK @ ALSA device list

### ISSUE THREAD

**Issue by Leocorp** [YoeDistro/meta-intel#1]
Hello, I am trying to build a yocto Image for a Simatic PC with an Intel-celeron processor. First of, building for the "generic-x86-64" it is able to boot up successfully even though the image can't seem to control the shutdown and reboots of the PC.
So I thought the optimized meta-intel layer might do the trick. However, after adding the layer and creating images for both core-2 and core-i7, I noticed that, at boot up, the PC gets stuck at:
"ALSA device list:"

I have tried removing "alsa" from the "MACHINE_FEATURES" in the x86-base.inc" file but that changes nothing. 

I was hoping someone could help resolve this issue. It's got me STUCK!!
Find attached a screen capture of the current issue.
![20191216_144502](https://user-images.githubusercontent.com/8627346/70911727-c5e76d80-2012-11ea-9c1c-11d7aa4bd20f.jpg)

**Comment by kraj** [comment]
Can you describe your build, are you using master or some release of yoe ?

**Comment by Leocorp** [comment]
I am using the "THUD" release of yoe and hence I also switched to the "THUD" header of the meta-intel layer in hopes to avoid any compatibility issues.

**Comment by kraj** [comment]
Ok is it
Possible for you to use Zeus release

**Comment by Leocorp** [comment]
I can try it out if you think that might resolve the issue. The thing I am also dependent on the meta-snap layer which seem to be stuck at this particular release (thud). Hence the reason I am trying to adapt everything to it.

**Comment by Leocorp** [comment]
Okay guys, the issue has been resolved. I changed the default kernel to 4.9 and also patched it to include and support additional hardware present on my PC.

**Comment by cbrake** [comment]
thanks for letting us know how you resolved it -- glad its working.
