### ISSUE TITLE
Booting from Hard-disk

### ISSUE THREAD

**Issue by bkpcoding** [YoeDistro/meta-intel#2]
Hey everyone,
I am currently trying to build the yocto image and boot it using "QEMU"  which uses intel-corei7-64 bsp layer on my intel corei7 vPro machine using Ubuntu 20.04 in VirtualBox, but when type the command "runqemu intel-corei7-64 core-image-sato wic", the interface loads up but gets stuck at "booting from hard disk".
![booting_from_harddisk](https://user-images.githubusercontent.com/59369344/123577962-cb467c00-d7a2-11eb-9862-5d95b558c514.png)

I have been using the hardknott branch and my one more thing although my computer shows virtualization is enabled i.e. intel vt is supported, when I run the command "$ grep -E 'svm|vmx' /proc/cpuinfo", to check if intel VT is enabled it shows no output.
Can someone help me through it? Do I have to change some other configurations than mentioned in the readme to run it in QEMU rather than using USB flash drive?
Thank you

**Comment by anujm1** [comment]
Try passing ovmf to runqemu.

**Comment by bkpcoding** [comment]
Thank you very much, I had been stuck in this from past week, now it runs. 
So the following command helped me to build the image for those who face the same issue,
$ runqemu intel-corei7-64 core-image-sato wic ovmf
