### ISSUE TITLE
Secure boot build issue : 'uefi-comboapp.bbclass .. function: create_uefiapps'

### ISSUE THREAD

**Issue by ChitlaLK** [YoeDistro/meta-intel#8]
Hi,  secure-boot build is failing with mention error, any thoughts would be helpful please. 
(Link fallowed : https://github.com/YoeDistro/meta-intel/blob/master/documentation/secureboot/README) 

- //Steps:
-  1)  git clone git://git.yoctoproject.org/poky -b dunfell
-  2)  cd poky
-  3) git clone https://github.com/YoeDistro/meta-intel.git -b dunfell
-  4) source oe-init-build-env 
-  5) cd ..
-  6) bitbake-layers add-layer meta-intel
-  7) bitbake core-image-minimal 

**// Build Issue :**

DEBUG: Executing python function do_uefiapp
DEBUG: Executing python function create_uefiapps
ERROR: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:create_uefiapps(d)
     0003:
File: '/home/test/poky/meta-intel/classes/uefi-comboapp.bbclass', lineno: 83, function: create_uefiapps
     0079:    pattern = d.expand('${DEPLOY_DIR_IMAGE}/${IMAGE_LINK_NAME}.boot*.efi')
     0080:    for old_efi in glob.glob(pattern):
     0081:        os.unlink(old_efi)
     0082:    uuid = d.getVar('DISK_SIGNATURE_UUID')
 *** 0083:    create_uefiapp(d, uuid=uuid)
     0084:}
     0085:
     0086:# This is intentionally split into different parts. This way, derived
     0087:# classes or images can extend the individual parts. We can also use
File: '/home/test/poky/meta-intel/classes/uefi-comboapp.bbclass', lineno: 48, function: create_uefiapp
     0044:    linux = '%s/%s' % (deploy_dir_image, d.getVar('KERNEL_IMAGETYPE'))
     0045:    initrd = '%s/initrd' % build_dir
     0046:
     0047:    stub_path = '%s/linux*.efi.stub' % deploy_dir_image
 *** 0048:    stub = glob.glob(stub_path)[0]
     0049:    m = re.match(r"\S*(ia32|x64)(.efi)\S*", os.path.basename(stub))
     0050:    app = "boot%s%s%s" % (m.group(1), app_suffix, m.group(2))
     0051:    executable = '%s/%s.%s' % (deploy_dir_image, image_link_name, app)
     0052:
Exception: IndexError: list index out of range

DEBUG: Python function create_uefiapps finished
DEBUG: Python function do_uefiapp finished

Regards,
Loki

**Comment by kraj** [comment]
Please report this to upstream meta-intel repo mailing list meta-intel@lists.yoctoproject.org
